-- Fresh PostgreSQL schema for Neon. Existing Oracle data is intentionally not migrated.
CREATE TABLE owners (
  owner_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name VARCHAR(100) NOT NULL, phone VARCHAR(20) NOT NULL UNIQUE,
  email VARCHAR(100) UNIQUE, address VARCHAR(250), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_owners_phone_digits CHECK (phone ~ '^[0-9]{10}$')
);
CREATE TABLE vehicles (
  vehicle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, owner_id BIGINT NOT NULL REFERENCES owners(owner_id),
  vehicle_number VARCHAR(20) NOT NULL UNIQUE, vehicle_type VARCHAR(20) NOT NULL CHECK (vehicle_type IN ('TWO_WHEELER','FOUR_WHEELER','HEAVY_VEHICLE')),
  brand VARCHAR(50) NOT NULL, model VARCHAR(50) NOT NULL, color VARCHAR(30), status VARCHAR(12) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE parking_zones (
  zone_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, zone_name VARCHAR(80) NOT NULL UNIQUE, description VARCHAR(200),
  base_rate_per_hour NUMERIC(8,2) NOT NULL CHECK (base_rate_per_hour > 0), status VARCHAR(12) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE slots (
  slot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, zone_id BIGINT NOT NULL REFERENCES parking_zones(zone_id), slot_code VARCHAR(20) NOT NULL UNIQUE,
  slot_type VARCHAR(20) NOT NULL CHECK (slot_type IN ('ANY','TWO_WHEELER','FOUR_WHEELER','HEAVY_VEHICLE')), status VARCHAR(15) NOT NULL DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE','OCCUPIED','RESERVED','MAINTENANCE')),
  current_vehicle_id BIGINT REFERENCES vehicles(vehicle_id), occupied_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(current_vehicle_id)
);
CREATE TABLE staff (
  staff_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, staff_name VARCHAR(100) NOT NULL, role VARCHAR(20) NOT NULL CHECK (role IN ('ATTENDANT','SUPERVISOR')),
  phone VARCHAR(20) NOT NULL UNIQUE, username VARCHAR(50) NOT NULL UNIQUE, password_hash VARCHAR(200) NOT NULL, status VARCHAR(12) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT ck_staff_phone_digits CHECK (phone ~ '^[0-9]{10}$')
);
CREATE TABLE entries (
  entry_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, vehicle_id BIGINT NOT NULL REFERENCES vehicles(vehicle_id), slot_id BIGINT NOT NULL REFERENCES slots(slot_id), staff_id BIGINT NOT NULL REFERENCES staff(staff_id), entry_time TIMESTAMPTZ NOT NULL DEFAULT NOW(), status VARCHAR(12) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','CLOSED'))
);
CREATE UNIQUE INDEX ux_entries_active_vehicle ON entries(vehicle_id) WHERE status = 'ACTIVE';
CREATE TABLE exits (
  exit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, entry_id BIGINT NOT NULL UNIQUE REFERENCES entries(entry_id), vehicle_id BIGINT NOT NULL REFERENCES vehicles(vehicle_id), slot_id BIGINT NOT NULL REFERENCES slots(slot_id), staff_id BIGINT NOT NULL REFERENCES staff(staff_id), exit_time TIMESTAMPTZ NOT NULL DEFAULT NOW(), duration_minutes INTEGER NOT NULL CHECK (duration_minutes > 0), fee_amount NUMERIC(10,2) NOT NULL CHECK (fee_amount >= 0), payment_status VARCHAR(12) NOT NULL DEFAULT 'UNPAID' CHECK (payment_status IN ('UNPAID','PAID')), reference_no VARCHAR(40) UNIQUE
);
CREATE TABLE fees (
  fee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, entry_id BIGINT NOT NULL UNIQUE REFERENCES entries(entry_id), vehicle_id BIGINT NOT NULL REFERENCES vehicles(vehicle_id), vehicle_type VARCHAR(20) NOT NULL, duration_minutes INTEGER NOT NULL CHECK (duration_minutes > 0), rate_per_hour NUMERIC(8,2) NOT NULL, fee_amount NUMERIC(10,2) NOT NULL, calculated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE payments (
  payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, fee_id BIGINT NOT NULL UNIQUE REFERENCES fees(fee_id), exit_id BIGINT NOT NULL UNIQUE REFERENCES exits(exit_id), amount_paid NUMERIC(10,2) NOT NULL CHECK (amount_paid > 0), payment_mode VARCHAR(15) NOT NULL CHECK (payment_mode IN ('CASH','UPI','CARD','NETBANKING')), reference_no VARCHAR(50) UNIQUE, paid_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE passes (
  pass_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, vehicle_id BIGINT NOT NULL REFERENCES vehicles(vehicle_id), pass_type VARCHAR(15) NOT NULL CHECK (pass_type IN ('WEEKLY','MONTHLY','YEARLY')), start_date DATE NOT NULL, end_date DATE NOT NULL CHECK (end_date >= start_date), status VARCHAR(12) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','EXPIRED')), pass_fee NUMERIC(10,2) NOT NULL CHECK (pass_fee >= 0), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE violations (
  violation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, vehicle_id BIGINT NOT NULL REFERENCES vehicles(vehicle_id), entry_id BIGINT REFERENCES entries(entry_id), violation_type VARCHAR(100) NOT NULL, fine_amount NUMERIC(10,2) NOT NULL CHECK (fine_amount >= 0), payment_status VARCHAR(12) NOT NULL DEFAULT 'UNPAID' CHECK (payment_status IN ('UNPAID','PAID')), issued_by BIGINT NOT NULL REFERENCES staff(staff_id), issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), paid_at TIMESTAMPTZ
);

CREATE VIEW vw_available_slots AS SELECT z.zone_name, s.slot_id, s.slot_code, s.slot_type, z.base_rate_per_hour FROM slots s JOIN parking_zones z ON z.zone_id=s.zone_id WHERE s.status='AVAILABLE' AND z.status='ACTIVE';
CREATE VIEW vw_occupied_slots AS SELECT z.zone_name, s.slot_id, s.slot_code, s.slot_type, v.vehicle_number, o.full_name AS owner_name, s.occupied_at FROM slots s JOIN parking_zones z ON z.zone_id=s.zone_id LEFT JOIN vehicles v ON v.vehicle_id=s.current_vehicle_id LEFT JOIN owners o ON o.owner_id=v.owner_id WHERE s.status='OCCUPIED';
CREATE VIEW vw_active_vehicles AS SELECT e.entry_id, v.vehicle_number, o.full_name AS owner_name, v.vehicle_type, z.zone_name, s.slot_code, e.entry_time FROM entries e JOIN vehicles v ON v.vehicle_id=e.vehicle_id JOIN slots s ON s.slot_id=e.slot_id JOIN parking_zones z ON z.zone_id=s.zone_id LEFT JOIN owners o ON o.owner_id=v.owner_id WHERE e.status='ACTIVE';
CREATE VIEW vw_currently_parked AS SELECT * FROM vw_active_vehicles;
CREATE VIEW vw_daily_revenue AS SELECT paid_at::date AS revenue_date, COUNT(*) AS payment_count, SUM(amount_paid) AS total_revenue FROM payments GROUP BY paid_at::date;
CREATE VIEW vw_unpaid_violations AS SELECT v.violation_id, veh.vehicle_number, o.full_name AS owner_name, v.violation_type, v.fine_amount, v.payment_status, s.staff_name AS issued_by_name, v.issued_at, v.paid_at FROM violations v JOIN vehicles veh ON veh.vehicle_id=v.vehicle_id LEFT JOIN owners o ON o.owner_id=veh.owner_id JOIN staff s ON s.staff_id=v.issued_by WHERE v.payment_status='UNPAID';
CREATE VIEW vw_active_passes AS SELECT p.pass_id, veh.vehicle_number, o.full_name AS owner_name, p.pass_type, p.start_date, p.end_date, p.pass_fee, p.status FROM passes p JOIN vehicles veh ON veh.vehicle_id=p.vehicle_id LEFT JOIN owners o ON o.owner_id=veh.owner_id WHERE p.status='ACTIVE' AND p.end_date >= CURRENT_DATE;
CREATE VIEW vw_pass_status AS SELECT status, COUNT(*) AS total_count FROM passes GROUP BY status;
CREATE VIEW vw_zone_occupancy AS SELECT z.zone_name, COUNT(s.slot_id) AS total_slots, COUNT(*) FILTER (WHERE s.status='OCCUPIED') AS occupied_slots, COUNT(*) FILTER (WHERE s.status='AVAILABLE') AS available_slots, CASE WHEN COUNT(s.slot_id)=0 THEN 0 ELSE ROUND((COUNT(*) FILTER (WHERE s.status='OCCUPIED')::numeric / COUNT(s.slot_id))*100,2) END AS occupancy_percent FROM parking_zones z LEFT JOIN slots s ON s.zone_id=z.zone_id GROUP BY z.zone_name;
CREATE VIEW vw_vehicle_history AS SELECT veh.vehicle_number, o.full_name AS owner_name, veh.vehicle_type, s.slot_code, e.entry_time, x.exit_time, x.duration_minutes, x.fee_amount, COALESCE(x.payment_status,'PARKED') AS payment_status FROM vehicles veh LEFT JOIN owners o ON o.owner_id=veh.owner_id LEFT JOIN entries e ON e.vehicle_id=veh.vehicle_id LEFT JOIN exits x ON x.entry_id=e.entry_id LEFT JOIN slots s ON s.slot_id=e.slot_id;
CREATE VIEW vw_fee_summary AS SELECT f.fee_id, f.entry_id, veh.vehicle_number, f.vehicle_type, f.duration_minutes, f.rate_per_hour, f.fee_amount, f.calculated_at, COALESCE(p.payment_status,'UNPAID') AS payment_status, p.paid_at FROM fees f JOIN vehicles veh ON veh.vehicle_id=f.vehicle_id LEFT JOIN payments p ON p.fee_id=f.fee_id;
