-- VPMS Oracle schema
-- Run this on a fresh schema.

CREATE TABLE owners (
  owner_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  full_name VARCHAR2(100) NOT NULL,
  phone VARCHAR2(20) NOT NULL,
  email VARCHAR2(100),
  address VARCHAR2(250),
  created_at DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT uq_owners_phone UNIQUE (phone),
  CONSTRAINT uq_owners_email UNIQUE (email)
);

CREATE TABLE vehicles (
  vehicle_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  owner_id NUMBER NOT NULL,
  vehicle_number VARCHAR2(20) NOT NULL,
  vehicle_type VARCHAR2(20) NOT NULL,
  brand VARCHAR2(50) NOT NULL,
  model VARCHAR2(50) NOT NULL,
  color VARCHAR2(30),
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL,
  created_at DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT uq_vehicles_number UNIQUE (vehicle_number),
  CONSTRAINT fk_vehicles_owner FOREIGN KEY (owner_id) REFERENCES owners (owner_id),
  CONSTRAINT ck_vehicles_type CHECK (vehicle_type IN ('TWO_WHEELER', 'FOUR_WHEELER', 'HEAVY_VEHICLE')),
  CONSTRAINT ck_vehicles_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE parking_zones (
  zone_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  zone_name VARCHAR2(80) NOT NULL,
  description VARCHAR2(200),
  base_rate_per_hour NUMBER(8, 2) NOT NULL,
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL,
  created_at DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT uq_parking_zones_name UNIQUE (zone_name),
  CONSTRAINT ck_parking_zones_rate CHECK (base_rate_per_hour > 0),
  CONSTRAINT ck_parking_zones_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE slots (
  slot_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  zone_id NUMBER NOT NULL,
  slot_code VARCHAR2(20) NOT NULL,
  slot_type VARCHAR2(20) NOT NULL,
  status VARCHAR2(15) DEFAULT 'AVAILABLE' NOT NULL,
  current_vehicle_id NUMBER,
  occupied_at DATE,
  created_at DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT uq_slots_code UNIQUE (slot_code),
  CONSTRAINT fk_slots_zone FOREIGN KEY (zone_id) REFERENCES parking_zones (zone_id),
  CONSTRAINT fk_slots_vehicle FOREIGN KEY (current_vehicle_id) REFERENCES vehicles (vehicle_id),
  CONSTRAINT uq_slots_vehicle UNIQUE (current_vehicle_id),
  CONSTRAINT ck_slots_type CHECK (slot_type IN ('ANY', 'TWO_WHEELER', 'FOUR_WHEELER', 'HEAVY_VEHICLE')),
  CONSTRAINT ck_slots_status CHECK (status IN ('AVAILABLE', 'OCCUPIED', 'RESERVED', 'MAINTENANCE'))
);

CREATE TABLE staff (
  staff_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  staff_name VARCHAR2(100) NOT NULL,
  role VARCHAR2(20) NOT NULL,
  phone VARCHAR2(20) NOT NULL,
  username VARCHAR2(50) NOT NULL,
  password_hash VARCHAR2(200) NOT NULL,
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL,
  created_at DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT uq_staff_phone UNIQUE (phone),
  CONSTRAINT uq_staff_username UNIQUE (username),
  CONSTRAINT ck_staff_role CHECK (role IN ('ADMIN', 'ATTENDANT', 'SUPERVISOR')),
  CONSTRAINT ck_staff_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE entries (
  entry_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  vehicle_id NUMBER NOT NULL,
  slot_id NUMBER NOT NULL,
  staff_id NUMBER NOT NULL,
  entry_time DATE DEFAULT SYSDATE NOT NULL,
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT fk_entries_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (vehicle_id),
  CONSTRAINT fk_entries_slot FOREIGN KEY (slot_id) REFERENCES slots (slot_id),
  CONSTRAINT fk_entries_staff FOREIGN KEY (staff_id) REFERENCES staff (staff_id),
  CONSTRAINT ck_entries_status CHECK (status IN ('ACTIVE', 'CLOSED'))
);

CREATE TABLE exits (
  exit_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  entry_id NUMBER NOT NULL,
  vehicle_id NUMBER NOT NULL,
  slot_id NUMBER NOT NULL,
  staff_id NUMBER NOT NULL,
  exit_time DATE DEFAULT SYSDATE NOT NULL,
  duration_minutes NUMBER NOT NULL,
  fee_amount NUMBER(10, 2) NOT NULL,
  payment_status VARCHAR2(12) DEFAULT 'UNPAID' NOT NULL,
  reference_no VARCHAR2(40),
  CONSTRAINT uq_exits_entry UNIQUE (entry_id),
  CONSTRAINT fk_exits_entry FOREIGN KEY (entry_id) REFERENCES entries (entry_id),
  CONSTRAINT fk_exits_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (vehicle_id),
  CONSTRAINT fk_exits_slot FOREIGN KEY (slot_id) REFERENCES slots (slot_id),
  CONSTRAINT fk_exits_staff FOREIGN KEY (staff_id) REFERENCES staff (staff_id),
  CONSTRAINT ck_exits_duration CHECK (duration_minutes > 0),
  CONSTRAINT ck_exits_fee CHECK (fee_amount >= 0),
  CONSTRAINT ck_exits_payment_status CHECK (payment_status IN ('UNPAID', 'PAID')),
  CONSTRAINT uq_exits_reference UNIQUE (reference_no)
);

CREATE TABLE fees (
  fee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  entry_id NUMBER NOT NULL,
  vehicle_id NUMBER NOT NULL,
  vehicle_type VARCHAR2(20) NOT NULL,
  duration_minutes NUMBER NOT NULL,
  rate_per_hour NUMBER(8, 2) NOT NULL,
  fee_amount NUMBER(10, 2) NOT NULL,
  calculated_at DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT uq_fees_entry UNIQUE (entry_id),
  CONSTRAINT fk_fees_entry FOREIGN KEY (entry_id) REFERENCES entries (entry_id),
  CONSTRAINT fk_fees_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (vehicle_id),
  CONSTRAINT ck_fees_vehicle_type CHECK (vehicle_type IN ('TWO_WHEELER', 'FOUR_WHEELER', 'HEAVY_VEHICLE')),
  CONSTRAINT ck_fees_duration CHECK (duration_minutes > 0),
  CONSTRAINT ck_fees_rate CHECK (rate_per_hour >= 0),
  CONSTRAINT ck_fees_amount CHECK (fee_amount >= 0)
);

CREATE TABLE payments (
  payment_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  fee_id NUMBER NOT NULL,
  exit_id NUMBER NOT NULL,
  amount_paid NUMBER(10, 2) NOT NULL,
  payment_mode VARCHAR2(15) NOT NULL,
  reference_no VARCHAR2(50),
  paid_at DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT uq_payments_fee UNIQUE (fee_id),
  CONSTRAINT uq_payments_exit UNIQUE (exit_id),
  CONSTRAINT fk_payments_fee FOREIGN KEY (fee_id) REFERENCES fees (fee_id),
  CONSTRAINT fk_payments_exit FOREIGN KEY (exit_id) REFERENCES exits (exit_id),
  CONSTRAINT ck_payments_amount CHECK (amount_paid > 0),
  CONSTRAINT ck_payments_mode CHECK (payment_mode IN ('CASH', 'UPI', 'CARD', 'NETBANKING')),
  CONSTRAINT uq_payments_reference UNIQUE (reference_no)
);

CREATE TABLE passes (
  pass_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  vehicle_id NUMBER NOT NULL,
  pass_type VARCHAR2(15) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL,
  pass_fee NUMBER(10, 2) NOT NULL,
  created_at DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT fk_passes_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (vehicle_id),
  CONSTRAINT ck_passes_type CHECK (pass_type IN ('WEEKLY', 'MONTHLY', 'YEARLY')),
  CONSTRAINT ck_passes_dates CHECK (end_date >= start_date),
  CONSTRAINT ck_passes_status CHECK (status IN ('ACTIVE', 'EXPIRED')),
  CONSTRAINT ck_passes_fee CHECK (pass_fee >= 0)
);

CREATE TABLE violations (
  violation_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  vehicle_id NUMBER NOT NULL,
  entry_id NUMBER,
  violation_type VARCHAR2(100) NOT NULL,
  fine_amount NUMBER(10, 2) NOT NULL,
  payment_status VARCHAR2(12) DEFAULT 'UNPAID' NOT NULL,
  issued_by NUMBER NOT NULL,
  issued_at DATE DEFAULT SYSDATE NOT NULL,
  paid_at DATE,
  CONSTRAINT fk_violations_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (vehicle_id),
  CONSTRAINT fk_violations_entry FOREIGN KEY (entry_id) REFERENCES entries (entry_id),
  CONSTRAINT fk_violations_staff FOREIGN KEY (issued_by) REFERENCES staff (staff_id),
  CONSTRAINT ck_violations_fine CHECK (fine_amount >= 0),
  CONSTRAINT ck_violations_status CHECK (payment_status IN ('UNPAID', 'PAID'))
);

CREATE UNIQUE INDEX ux_entries_active_vehicle
  ON entries (CASE WHEN status = 'ACTIVE' THEN vehicle_id END);

CREATE INDEX idx_vehicles_owner ON vehicles (owner_id);
CREATE INDEX idx_slots_zone_status ON slots (zone_id, status);
CREATE INDEX idx_entries_vehicle_status ON entries (vehicle_id, status);
CREATE INDEX idx_entries_slot_status ON entries (slot_id, status);
CREATE INDEX idx_fees_vehicle ON fees (vehicle_id);
CREATE INDEX idx_payments_paid_at ON payments (paid_at);
CREATE INDEX idx_passes_vehicle_status ON passes (vehicle_id, status);
CREATE INDEX idx_violations_vehicle_status ON violations (vehicle_id, payment_status);
